swagger: "2.0"
info:
  description: "API endpoints for my instagram clone"
  version: "1.0.0"
  title: "Instagram Clone"


host: "igclone.example"
basePath: "/"
tags:
- name: "Profile"
  description: "Profile Endpoints"
- name: "Pictures"
  description: "Picture Endpoints"
schemes:
- "https"
- "http"
paths:
  /profile:
    post:
      tags:
      - "Profile"
      summary: "Create a new profile"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "error"
    put:
      tags:
      - "Profile"
      summary: "Update an existing profile"
      responses:
        "200":
          description: "successful operation"
        "404":
          description: "error"

  /profile/{profileId}:
    get:
      tags:
      - "Profile"
      summary: "Find Profile"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Profile not found"      
    delete:
      tags:
      - "Profile"
      summary: "Delete Profile"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Profile not found" 

  /profileID/pictures:
    get:
      tags:
      - "Pictures"
      summary: "Find all pictures from a profile"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Profile not found"

  /profileID/{picturesID}:
    post:
      tags:
      - "Pictures"
      summary: "Post a picture"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Profile not found"
    delete:
      tags:
      - "Pictures"
      summary: "Deletes a picture"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Picture not found"
    put:
      tags:
      - "Pictures"
      summary: "Updates a picture"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Picture not found"
    get:
      tags:
      - "Pictures"
      summary: "Gets a picture"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Picture not found"
