name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  test_suit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirement.txt]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src
          python -m unittest discover -s tests/